### ISSUE TITLE
one click oomph installer - yes!

### ISSUE THREAD

**Issue by dhartford** [themetalone/oomph-fork#1]
So, I've seen a lot of people creating new indexes following the redirect, but few are focusing on the catch phrase "one click install", which I infer as the first-page/front-page, something I'm quite interested in.

Do you have a website (github.io?) that talks about your intent with pictures?

**Comment by themetalone** [comment]
No, not yet. This project (although the repo is older) is at its start. But ideas will follow

**Comment by themetalone** [comment]
At the moment I'm trying to figure out what does what in the code since it lacks any documentatoin
