### ISSUE TITLE
eclipse-inst is not marked as executable

### ISSUE THREAD

**Issue by maybeec** [themetalone/oomph-fork#4]
I am not sure, wheather the normal eclipse installer is distributed by zip or tgz. However, tgz will keep the file properties while zip does not. So it would be nice to provide the linux installer as tgz to mark  eclipse-inst directly as executable.

**Comment by sobkowiak** [comment]
If you use the assembly maven plugin to build the zip file the executable flag in the zip files should be preserved for the linux scripts.

**Comment by themetalone** [comment]
The zips are created via maven. Could the build on windows be responsible for that?

**Comment by maybeec** [comment]
yes, that might be. Just setup a travis build if possible.
Then this error should be gone, right?

**Comment by maybeec** [comment]
persists with 1.6.0-prerelease

**Comment by themetalone** [comment]
done by travis
