### ISSUE TITLE
After upgrade to v1.6.0 oasp products are gone

### ISSUE THREAD

**Issue by maybeec** [themetalone/oomph-fork#6]
I installed the custom tasks, which seem to also install the update of 1.6.0.
The result was, that the oasp product catalog was gone. Maybe not possible to prevent, so upgrade to not as soon as possible. (see also #5)

**Comment by maybeec** [comment]
btw. and all the customizations ;)

**Comment by themetalone** [comment]
Solved with the self hosted update site
