### ISSUE TITLE
Add SetupProperty for launch automatically, offline, and use bundle pools if possible

### ISSUE THREAD

**Issue by maybeec** [themetalone/oomph-fork#9]
Please check if there are already [SetupProperties](https://github.com/themetalone/oomph-fork/blob/2252b732ca5ccbc5cbb63c79257eb32c3de07c88/plugins/org.eclipse.oomph.setup/src/org/eclipse/oomph/internal/setup/SetupProperties.java) for disabling launch automatically, offline, and use bundle pools.

If not, add some to make adjustments to globally provided installer even easier.
We want to add a PR to Oomph for that as well.

**Comment by themetalone** [comment]
Done for 'launch automatically' and 'p2 pool' on development branch. In the SetuProperties is a value for the 'offline'.

I'll just need to find out how to contribute to oomph

**Comment by maybeec** [comment]
Then we should switch to these properties to be set in the ini file rather than updating Code! Great Job.

Basically, as far as I understood it, you simply have to clone Oomph by Oomph Installer such that you will get the complete setup. Then you commit stuff you want to contribute and choose Team>Remote>Push to Gerrit in the eclipse context menu. However, I have not yet done it. So happy contributing :)

**Comment by themetalone** [comment]
Changes are contributed to oomph. LaunchAutomatically and P2Pool are under review from the developers

**Comment by maybeec** [comment]
but not yet in your local release here?

**Comment by maybeec** [comment]
can you link the gerrit topics here?

**Comment by themetalone** [comment]
They were.. but I think during installation of the needed tasks the installer updates itself with it and removes my changes. I'm trying right now to establish a update site for the eclipse installer in this repos gh-pages to prevent that

**Comment by themetalone** [comment]
https://git.eclipse.org/r/#/c/85117/
